// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package api

// RedisString defines model for RedisString.
type RedisString string

// OkSuccessResponse defines model for OkSuccessResponse.
type OkSuccessResponse string

// PostSetKeyJSONRequestBody defines body for PostSetKey for application/json ContentType.
type PostSetKeyJSONRequestBody RedisString
